create table brands
(
    id          bigint generated by default as identity,
    description TEXT,
    logo_url    varchar(255),
    name        varchar(255) not null,
    slug        varchar(255) not null unique,
    website     varchar(255),
    primary key (id)
);
create table categories
(
    id          bigint generated by default as identity,
    parent_id   bigint,
    level       integer      not null,
    description varchar(1000),
    image_url   varchar(255),
    name        varchar(255) not null,
    slug        varchar(255) not null unique,
    primary key (id)
);
create table gifticon_images
(
    id            bigint generated by default as identity,
    gifticon_id   bigint       not null,
    alt_text      varchar(255),
    url           varchar(255) not null,
    display_order integer      not null,
    is_primary    boolean      not null,
    primary key (id)
);
create table gifticon_likes
(
    id          bigint generated by default as identity,
    user_id     bigint       not null,
    gifticon_id bigint       not null,
    created_at  timestamp(6) not null,
    primary key (id)
);
create table gifticon_prices
(
    id          bigint generated by default as identity,
    gifticon_id bigint         not null unique,
    base_price  numeric(19, 2) not null,
    currency    varchar(3)     not null,
    sale_price  numeric(19, 2),
    primary key (id)
);
create table gifticon_tags
(
    gifticon_id bigint not null,
    tag_id      bigint not null
);
create table gifticons
(
    id          bigint generated by default as identity,
    seller_id   bigint       not null,
    category_id bigint       not null,
    due_date date not null,
    brand_id    bigint       not null,
    buyer_id    bigint,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6),
    description TEXT,
    name        varchar(255),
    slug        varchar(255),
    status      varchar(255) not null check (status in ('ON_SALE', 'SOLD_OUT', 'DELETED')),
    primary key (id)
);
create table reviews
(
    id          bigint generated by default as identity,
    gifticon_id bigint       not null,
    user_id     bigint       not null,
    title       varchar(200),
    content     TEXT         not null,
    rating      integer      not null,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6),
    primary key (id)
);
create table search_keywords
(
    id         bigint generated by default as identity,
    keyword    varchar(255) not null,
    created_at timestamp(6) not null,
    primary key (id)
);
create table tags
(
    id   bigint generated by default as identity,
    name varchar(255) not null unique,
    slug varchar(255) not null unique,
    primary key (id)
);
create table users
(
    id                bigint generated by default as identity,
    username          varchar(255),
    nickname          varchar(255),
    profile_image_url varchar(255),
    primary key (id)
);
alter table if exists categories
    add constraint fk_category_parent
        foreign key (parent_id)
            references categories;
alter table if exists gifticon_images
    add constraint fk_gifticon_image_gifticon
        foreign key (gifticon_id)
            references gifticons;
alter table if exists gifticon_likes
    add constraint fk_gifticon_like_gifticon
        foreign key (gifticon_id)
            references gifticons;
alter table if exists gifticon_likes
    add constraint fk_gifticon_like_user
        foreign key (user_id)
            references users;
alter table if exists gifticon_prices
    add constraint fk_gifticon_price_gifticon
        foreign key (gifticon_id)
            references gifticons;
alter table if exists gifticon_tags
    add constraint fk_tag_gifticon
        foreign key (tag_id)
            references tags;
alter table if exists gifticon_tags
    add constraint fk_gifticon_tag
        foreign key (gifticon_id)
            references gifticons;
alter table if exists gifticons
    add constraint fk_gifticon_brand
        foreign key (brand_id)
            references brands;
alter table if exists gifticons
    add constraint fk_gifticon_buyer
        foreign key (buyer_id)
            references users;
alter table if exists gifticons
    add constraint fk_gifticon_category
        foreign key (category_id)
            references categories;
alter table if exists gifticons
    add constraint fk_gifticon_seller
        foreign key (seller_id)
            references users;
alter table if exists reviews
    add constraint fk_gifticon_review_gifticon
        foreign key (gifticon_id)
            references gifticons;
alter table if exists reviews
    add constraint fk_user_review
        foreign key (user_id)
            references users;
alter table users
    add constraint users_pk
        unique (nickname);
alter table users
    add constraint users_pk_2
        unique (username);

