create table brands
(
    id          bigint generated by default as identity,
    description TEXT,
    logo_url    varchar(255),
    name        varchar(255) not null,
    slug        varchar(255) not null unique,
    website     varchar(255),
    primary key (id)
);
create table categories
(
    level       integer      not null,
    id          bigint generated by default as identity,
    parent_id   bigint,
    description varchar(1000),
    image_url   varchar(255),
    name        varchar(255) not null,
    slug        varchar(255) not null unique,
    primary key (id)
);
create table gifticon_categories
(
    category_id bigint not null,
    gifticon_id bigint not null
);
create table gifticon_images
(
    display_order integer      not null,
    is_primary    boolean      not null,
    gifticon_id   bigint       not null,
    id            bigint generated by default as identity,
    alt_text      varchar(255),
    url           varchar(255) not null,
    primary key (id)
);
create table gifticon_likes
(
    created_at  timestamp(6) not null,
    gifticon_id bigint       not null,
    id          bigint generated by default as identity,
    user_id     bigint       not null,
    primary key (id)
);
create table gifticon_prices
(
    base_price  numeric(19, 2) not null,
    currency    varchar(3)     not null,
    sale_price  numeric(19, 2),
    gifticon_id bigint         not null unique,
    id          bigint generated by default as identity,
    primary key (id)
);
create table gifticon_tags
(
    gifticon_id bigint not null,
    tag_id      bigint not null
);
create table gifticons
(
    brand_id    bigint       not null,
    buyer_id    bigint,
    created_at  timestamp(6) not null,
    id          bigint generated by default as identity,
    seller_id   bigint       not null,
    updated_at  timestamp(6),
    description TEXT,
    name        varchar(255),
    slug        varchar(255),
    status      varchar(255) not null check (status in ('ON_SALE', 'SOLD_OUT', 'DELETED')),
    primary key (id)
);
create table reviews
(
    rating      integer      not null,
    created_at  timestamp(6) not null,
    gifticon_id bigint       not null,
    id          bigint generated by default as identity,
    updated_at  timestamp(6),
    user_id     bigint       not null,
    title       varchar(200),
    content     TEXT         not null,
    primary key (id)
);
create table search_keywords
(
    created_at timestamp(6) not null,
    id         bigint generated by default as identity,
    keyword    varchar(255) not null,
    primary key (id)
);
create table tags
(
    id   bigint generated by default as identity,
    name varchar(255) not null unique,
    slug varchar(255) not null unique,
    primary key (id)
);
create table users
(
    id                bigint generated by default as identity,
    nickname          varchar(255),
    profile_image_url varchar(255),
    username          varchar(255),
    primary key (id)
);
alter table if exists categories
    add constraint fk_category_parent
    foreign key (parent_id)
    references categories;
alter table if exists gifticon_categories
    add constraint fk_category_gifticon
    foreign key (category_id)
    references categories;
alter table if exists gifticon_categories
    add constraint fk_gifticon_category
    foreign key (gifticon_id)
    references gifticons;
alter table if exists gifticon_images
    add constraint fk_gifticon_image_gifticon
    foreign key (gifticon_id)
    references gifticons;
alter table if exists gifticon_likes
    add constraint fk_gifticon_like_gifticon
    foreign key (gifticon_id)
    references gifticons;
alter table if exists gifticon_likes
    add constraint FK6mtkmplpnltm78doqcolpm47j
    foreign key (user_id)
    references users;
alter table if exists gifticon_prices
    add constraint fk_gifticon_price_gifticon
    foreign key (gifticon_id)
    references gifticons;
alter table if exists gifticon_tags
    add constraint fk_tag_gifticon
    foreign key (tag_id)
    references tags;
alter table if exists gifticon_tags
    add constraint fk_gifticon_tag
    foreign key (gifticon_id)
    references gifticons;
alter table if exists gifticons
    add constraint fk_gifticon_brand
    foreign key (brand_id)
    references brands;
alter table if exists gifticons
    add constraint fk_gifticon_buyer
    foreign key (buyer_id)
    references users;
alter table if exists gifticons
    add constraint fk_gifticon_seller
    foreign key (seller_id)
    references users;
alter table if exists reviews
    add constraint fk_gifticon_review_gifticon
    foreign key (gifticon_id)
    references gifticons;
alter table if exists reviews
    add constraint fk_user_review
    foreign key (user_id)
    references users;